[package]
name = "quantsim_core"
version = "0.2.1"
edition = "2021"
authors = ["Ben Schneider"]
license = "MIT OR Apache-2.0"
description = "A quantum circuit simulator"
repository = "https://github.com/benschneider/quantum_algorithm_simulator"
keywords = ["quantum", "simulation", "circuit", "physics", "education"]
categories = ["science", "simulation"]

[dependencies]
approx = "0.5.1"
dyn-clone = "1.0.20"
getrandom = { version = "0.2.16", features = ["js"] }
log = "0.4.28"
nalgebra = { version = "0.34.1", features = ["serde-serialize", "sparse"] }
nalgebra-sparse = { version = "0.11.0", features = ["serde-serialize"] }
num-complex = "0.4.6"
num-traits = "0.2.19"
rand = "0.8.5"
rayon = "1.11.0"
serde = { version = "1.0.226", features = ["derive"] }
serde_json = "1.0.145"
smallvec = { version = "1.15.1", features = ["serde"] }
strum = { version = "0.27.2", features = ["derive"] }
include_dir = "0.7.3"

[build-dependencies]

[dev-dependencies]
env_logger = "0.11.8"
proptest = "1.8.0"

[profile.release]
opt-level = 3 # fast and small wasm

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
